path:
  mean_csv_path: "domain_means.csv"
  cov_csv_path: "domain_covariances.csv"
  
senario:
  pattern_id: "previousresearch_2_1"
  weight_id: "relative_importance"
  model_id: "linear"

hyperparam:
  alpha: 1  
  split_ratio: 1
  n_trial: 1
  n_features: 10
  n_split: 5

datasettings:
  target_number: 210
  source1_number: 36
  source2_number: 24
  true_coffience:
    - [0,1,1,1,1,1,1,1,1,1,1] 