path:
  mean_csv_path: "domain_means.csv"
  cov_csv_path: "domain_covariances.csv"
  
senario:
  pattern_id: "senario_3"

hyperparam:
  alpha: 1  
  split_ratio: 1
  n_trial: 100
  n_features: 2
  n_split: 5

datasettings:
  target_number: 210
  source1_number: 54
  source2_number: 36
  true_coffience:
    - [1.5,-2.0,0.8] 